image: gitpod/workspace-full-vnc

ports:
  - port: 4000           # pharo language server
    onOpen: ignore
  - port: 5900           # standard vnc viewer - not used in this repo
    onOpen: ignore
  - port: 6080           # novnc viewer to workspace desktop
    onOpen: open-browser

tasks:
  - name: pharo
    init: ./get-pharo-launcher.sh
    command: HOME=$(pwd) ./pharolauncher/pharo-launcher

vscode:
  extensions:
    - badetitou.pharo-language-server@0.0.7:OW5PdTkSTcQHDTeJzYEG/w==
